#ifndef GAMEPADCODES_HPP
#define GAMEPADCODES_HPP


// taken from glfw3.h

#define AE_GAMEPAD_BUTTON_A               0
#define AE_GAMEPAD_BUTTON_B               1
#define AE_GAMEPAD_BUTTON_X               2
#define AE_GAMEPAD_BUTTON_Y               3
#define AE_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define AE_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define AE_GAMEPAD_BUTTON_BACK            6
#define AE_GAMEPAD_BUTTON_START           7
#define AE_GAMEPAD_BUTTON_GUIDE           8
#define AE_GAMEPAD_BUTTON_LEFT_THUMB      9
#define AE_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define AE_GAMEPAD_BUTTON_DPAD_UP         11
#define AE_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define AE_GAMEPAD_BUTTON_DPAD_DOWN       13
#define AE_GAMEPAD_BUTTON_DPAD_LEFT       14
#define AE_GAMEPAD_BUTTON_LAST            AE_GAMEPAD_BUTTON_DPAD_LEFT

#define AE_GAMEPAD_BUTTON_CROSS       AE_GAMEPAD_BUTTON_A
#define AE_GAMEPAD_BUTTON_CIRCLE      AE_GAMEPAD_BUTTON_B
#define AE_GAMEPAD_BUTTON_SQUARE      AE_GAMEPAD_BUTTON_X
#define AE_GAMEPAD_BUTTON_TRIANGLE    AE_GAMEPAD_BUTTON_Y


#define AE_GAMEPAD_AXIS_LEFT_X        0
#define AE_GAMEPAD_AXIS_LEFT_Y        1
#define AE_GAMEPAD_AXIS_RIGHT_X       2
#define AE_GAMEPAD_AXIS_RIGHT_Y       3
#define AE_GAMEPAD_AXIS_LEFT_TRIGGER  4
#define AE_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define AE_GAMEPAD_AXIS_LAST          AE_GAMEPAD_AXIS_RIGHT_TRIGGER

#endif
