name: C++ manual trigger

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
        - distribution

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install stuff
      run: sudo apt update && sudo apt install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglew-dev gcc-12

    - name: configure
      run: python scripts/Setup.py

    - name: build
      run: make config=debug all

    - name: package
      run: tar -czvf CrankEngine-dbg_linux.tar.gz bin/Debug-linux-x86_64/Crank/

    - name: upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "CrankEngine-dbg.linux"
        path: "./CrankEngine-dbg.linux.zip"



  build-windows:
    runs-on: windows-latest

    steps:
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: configure
      run: python scripts/Setup.py

    - name: build
      run: msbuild

    - name: package
      run: zip -r CrankEngine-dbg_windows.zip bin/Debug-windows-x86_64/Crank/

    - name: upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "CrankEngine-dbg.windows"
        path: "./CrankEngine-dbg.windows.zip"
